In [18]:
# Compute the Frobenius Norm of Matrix & Visualize
import numpy as np

A = np.random.rand(3, 3)
A_norm = np.linalg.norm(A, ord="fro") #fro = Frobenius Normalization, also np's default

print(f"Matrix A: \n{A}") 
print(f"\nFrobenius Norm of A: {A_norm:.3f}") #rounded to 3 decimal places

Matrix A: 
[[0.25764093 0.81712906 0.64466427]
 [0.94457883 0.09975614 0.69580896]
 [0.29214404 0.731528   0.53210659]]

Frobenius Norm of A: 1.855
